### ISSUE TITLE
READ Before Using This Script

### ISSUE THREAD

**Issue by elieven** [dvingerh/tiktok-dl#1]
```
! Unexpected response by API endpoint, retrying (1).

! Unexpected response by API endpoint, retrying (2).

! Unexpected response by API endpoint, retrying (3).

! Maximum retries exceeded, exiting.
```

**Comment by dvingerh** [comment]
Looks like solution isn't suitable for wide usage as device id's and stuff get blocked. As such this repo will be archived.

**Comment by dvingerh** [comment]
Reopened and added an announcement in the README with a brief explanation on how to obtain the required information this script needs to function. Any other questions regarding this matter will likely not be responded to.
